export const LOGIN_CHAT_APP = 'LOGIN_CHAT_APP';
export const LOG_OUT_CHAT_APP = 'LOG_OUT_CHAT_APP';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SELECTED_FRIEND_CHATING = 'SELECTED_FRIEND_CHATING';
export const SENDING_MESSAGE = 'SENDING_MESSAGE';
export const CHANGE_FRIEND_STAR_STATE  ='CHANGE_FRIEND_STAR_STATE';